### ISSUE TITLE
运行有个问题

### ISSUE THREAD

**Issue by shyboy0358** [Jornason/bitfinex_echarts#1]
{
  "_system": "geekree api system",
  "result": {
    "err": "error happened",
    "err_msg": [
      "bitfinex No market symbol ETH/USDT"
    ],
    "err_type": "ExchangeError"
  }
}

**Comment by Jornason** [comment]
readme.md 依赖包安装
pip install pandas0.22.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install ccxt1.17.490 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install requests2.18.4 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install PyEmail -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install pysocks1.6.6 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install pytz -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install requests -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install pprint -i https://pypi.tuna.tsinghua.edu.cn/simple
